export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_SIGNUP = 'RESET_SIGNUP';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_AUTO = 'LOGIN_AUTO';
export const LOGOUT = 'LOGOUT'

export const LOAD_SPACES = 'LOAD_SPACES';
export const LOAD_SPACES_SUCCESS = 'LOAD_SPACES_SUCCESS';
export const LOAD_SPACES_FAILED = 'LOAD_SPACES_FAILED';

export const FOLLOW_SPACE = 'FOLLOW_SPACE';
export const FOLLOW_SPACE_SUCCESS = 'FOLLOW_SPACE_SUCCESS';
export const FOLLOW_SPACE_FAILED = 'FOLLOW_SPACE_FAILED';
export const REMOVE_SPACE = 'REMOVE_SPACE';

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';

export const LOAD_ANSWERS = 'LOAD_ANSWERS';
export const LOAD_ANSWERS_SUCCESS = 'LOAD_ANSWERS_SUCCESS';
export const LOAD_ANSWERS_FAILED = 'LOAD_ANSWERS_FAILED';

export const VOTE_ANSWER_SUCCESS = 'VOTE_ANSWER_SUCCESS';
export const VOTE_ANSWER_FAILED = 'VOTE_ANSWER_FAILED';

export const ADD_COMMENT_START = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMNETS_SUCCESS';
export const LOAD_COMMENTS_FAILED = 'LOAD_COMMNETS_FAILED';

export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
export const LOAD_USER_START = 'LOAD_USER_START';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

export const FOLLOW_USER_START = 'FOLLOW_USER_START';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILED = 'FOLLOW_USER_FAILED';
export const REMOVE_USER = 'REMOVE_USER';




