export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_SIGNUP = 'RESET_SIGNUP';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_AUTO = 'LOGIN_AUTO';

export const LOAD_SPACES = 'LOAD_SPACES';
export const LOAD_SPACES_SUCCESS = 'LOAD_SPACES_SUCCESS';
export const LOAD_SPACES_FAILED = 'LOAD_SPACES_FAILED';

export const FOLLOW_SPACE = 'FOLLOW_SPACE';
export const FOLLOW_SPACE_SUCCESS = 'FOLLOW_SPACE_SUCCESS';
export const FOLLOW_SPACE_FAILED = 'FOLLOW_SPACE_FAILED';

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';

export const LOAD_ANSWERS = 'LOAD_ANSWERS';
export const LOAD_ANSWERS_SUCCESS = 'LOAD_ANSWERS_SUCCESS';
export const LOAD_ANSWERS_FAILED = 'LOAD_ANSWERS_FAILED';
